### ISSUE TITLE
Remove template resource as requested by Azure Marketplace

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#135]
In mainTemplate.json
Remove the Microsoft.Resources/deployments resource that has this name and type:

        "name": "pid-5990c833-d17a-5616-8ab3-144d90fea6e9",
        "type": "Microsoft.Resources/deployments",

Full test is only possible once the template is published to Azure Marketplace

**Comment by Arshpreet1002** [comment]
Where is this file "mainTemplate.json" and which pipeline do i need to create/test for this.

**Comment by robe070** [comment]
`git@github.com:lansa/azure-quickstart-templates.git`

`\GitHub\azure-quickstart-templates\lansa-vmss-windows-autoscale-sql-database\mainTemplate.json`

To test it just raise a PR. The CI pipeline will test it sufficiently.

**Comment by Arshpreet1002** [comment]
I have made changes to the mainTemplate.json and Tested it locally Which is working fine.
<img width="721" alt="Working_fine" src="https://user-images.githubusercontent.com/84080625/126150557-b6fd14f9-c9f0-4ff2-90af-70a68c53125c.PNG">

But ,After Creating PR The pipeline is failing and I am guessing it is failing due to other Template that is sqlserverTemplate.json
And showing the error of api versions.
After Changing the Versions and testing locally The validation is passed.
<img width="419" alt="validation" src="https://user-images.githubusercontent.com/84080625/126151960-727b80c6-42ee-49be-833a-916c3e0475be.PNG">

Can I edit the template(sqlServerTemplate.json) and the test the pipeline. Attaching the Screenshot for your reference.

**Comment by robe070** [comment]
I like your evidence of work done. It makes my task much much easier. Thank you.

Yes, check in the sqlserverTemplate.json file
