### ISSUE TITLE
P1 Test Production Image using the stack

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#34]
Requires the image to be published. Architect will notify when thats complete. This will be available by Monday 10th August.

Create a stack in US East and run the tests described in #7, but on the **Production** image, NOT Preview and NOT Custom Image
This should take about 1 hour with most of the time just waiting for the stack to be created.

**Comment by ashutosh-kumar1** [comment]
@rob, I was able to deploy the template using production image.
Please find attached
- Log
[production image deployment log.txt](https://github.com/robe070/cookbooks/files/5049533/production.image.deployment.log.txt)

- Screenshot
![production image deployment](https://user-images.githubusercontent.com/67790012/89760883-dea91400-db0a-11ea-89cc-37ebbf6bb16d.PNG)

I also have a script to execute the URLs provided in issue #7 which  executed and got the result:
PS W:\Accolite\robe070\cookbooks\scripts> w:\Accolite\robe070\cookbooks\Tests\TestURLs.ps1
W:\Accolite\robe070\cookbooks\Tests\TestURLs.ps1
200
200
200
200
Successfully tested all URL(s)

Since there are still some modifications needed in this file, so I have not committed it yet. Also, I have tested the URLs manually and they worked fine.
Please review the same. Maybe thereafter we can close phase 1.
