### ISSUE TITLE
P4 Beautified database type parameters

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#43]

**Comment by ashutosh-kumar1** [comment]
@robe070, Please provide a description of what needs to be done as a part of this issue?

**Comment by robe070** [comment]
I get emails when you @mention me. No need to also Slack me too.

This is just about separating out new and existing parameters and improving the validation of related parameters, all of which has been done or is being done.

**Comment by ashutosh-kumar1** [comment]
It's my bad. Sorry about that. Will take care of it.

**Comment by ashutosh-kumar1** [comment]
@robe07, This is also incorporated in the database blade of the solution template. Should this issue be marked as closed?

**Comment by robe070** [comment]
There has been an omission. The database type parameter in the UI needs to be displaying the options as "SQL Server", "Azure SQL Database", and "MySQL". Can this be done in the UI with mapping to the actual template parameter values? Or does the template need to be changed to accept these values and have the mapping done in the template? It would be better for the former if there is lots of usage of the database type in the pipeline. If not, then would be good to change the template too.

**Comment by ashutosh-kumar1** [comment]
@robe070, Yes, the changes can be made in the template file where the list and values visible in the UI will be as mentioned above but the values passed will be the one the parameter file accepts.
One more confirmation is needed. Currently, on selecting 'new' in the 'Database New/Existing' field, the 'database type' field is hidden. This is because we will only create an Azure SQL database in this case and therefore it will not be correct to allow user to alter the value of database type. Hope this behavior is fine.

**Comment by ashutosh-kumar1** [comment]
@robe070, The required changes were done as a part of PR: https://github.com/lansa/azure-quickstart-templates/pull/10. Please let me know if anything else needs to be done as part of this issue. Please close this if the requirements are met.
